# Generated by Django 5.2.1 on 2025-05-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('agency', models.CharField(blank=True, max_length=100)),
                ('join_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], max_length=10)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalties.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalties.artist')),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Spotify', 'Spotify'), ('Apple', 'Apple Music'), ('YouTube', 'YouTube')], max_length=50)),
                ('stream_date', models.DateField()),
                ('stream_count', models.PositiveIntegerField()),
                ('payout_per_stream', models.DecimalField(decimal_places=6, max_digits=10)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='royalties.track')),
            ],
        ),
    ]
