# Generated by Django 5.2.1 on 2025-05-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('royalties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltyrecord',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='royaltyrecord',
            name='platform',
            field=models.CharField(choices=[('spotify', 'Spotify'), ('apple', 'Apple Music'), ('youTube', 'YouTube')], max_length=50),
        ),
    ]
